name: Format & Lint

on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'test'
  pull_request:
    branches:
      - 'main'
      - 'staging'
      - 'test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
        run: npm install --force
      - name: Format
        run: npm run format --if-present
      - name: Lint
        run: npm run lint --if-present